# Generated by Django 5.2.6 on 2025-09-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.IntegerField()),
                ('room_type', models.CharField(choices=[('0', 'Standard'), ('1', 'Basic'), ('2', 'Deluxe')], default='0', max_length=1)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('0', 'Available'), ('1', 'Booked'), ('2', 'Maintenance')], default='0', max_length=1)),
                ('description', models.TextField()),
                ('floor', models.IntegerField()),
                ('images', models.TextField()),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
        ),
    ]
