# Generated by Django 5.2.6 on 2025-09-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
