# Generated by Django 5.2.6 on 2025-09-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
